version: 2
jobs:
  build:
    docker:
      - image: cypress/browsers:chrome67
        environment:
          TERM: xterm

    working_directory: ~/root

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache

      - run:
          name: Installing dependencies
          command: npm ci

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache

      - run:
          name: Unit tests
          command: npm run test

      - run:
          name: Run Server
          command: npm start
          background: true

      - run:
          name: Integration tests
          command: npm run e2e
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots