version: 2

jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm
    environment:
      - NODE_ENV: test
    parallelism: 1
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache

      - run:
        name: Run e2e tests
        command: npm run e2e

      - store_test_results:
          path: multiple-results

      - run:
          name: Run tests
          command: npm t

      
